#!/usr/bin/env bash
# Bootstrap Jarvis on Pop!_OS / Ubuntu.
set -euo pipefail

cd "$(dirname "$0")/.."

echo "== System packages =="
sudo apt update
sudo apt install -y \
    build-essential \
    pkg-config \
    cmake \
    clang \
    libdbus-1-dev \
    libssl-dev \
    libespeak-ng-dev \
    libasound2-dev \
    libpipewire-0.3-dev \
    brightnessctl \
    libnotify-bin \
    xdg-desktop-portal-gtk \
    playerctl \
    wmctrl \
    xdotool \
    wget

echo "== Rust toolchain =="
if ! command -v cargo >/dev/null 2>&1; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable
    # shellcheck disable=SC1090
    source "$HOME/.cargo/env"
fi

echo "== Models =="
models_dir="${XDG_DATA_HOME:-$HOME/.local/share}/jarvis/models"
mkdir -p "$models_dir"

# whisper.cpp medium model (multilingual, ~1.5 Go) — default. Markedly less
# hallucination on FR than `small`. `small` is kept as a lightweight fallback.
whisper_med_url="https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.bin"
[ -f "$models_dir/ggml-medium.bin" ] || wget -O "$models_dir/ggml-medium.bin" "$whisper_med_url"
whisper_url="https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.bin"
[ -f "$models_dir/ggml-small.bin" ] || wget -O "$models_dir/ggml-small.bin" "$whisper_url"

# Qwen2.5-3B Instruct GGUF (Q4_K_M).
llm_url="https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q4_k_m.gguf"
[ -f "$models_dir/qwen2.5-3b-instruct-q4_k_m.gguf" ] || \
    wget -O "$models_dir/qwen2.5-3b-instruct-q4_k_m.gguf" "$llm_url"

# openWakeWord pipeline (3 ONNX files: mel + embedding + wake) — all from
# the v0.5.1 release. The mel and embedding models are shared across every
# wake word; the third model is the wake word itself ("Hey Jarvis").
oww_base="https://github.com/dscripka/openWakeWord/releases/download/v0.5.1"
for f in melspectrogram.onnx embedding_model.onnx hey_jarvis_v0.1.onnx; do
    [ -f "$models_dir/$f" ] || curl -fsSL -o "$models_dir/$f" "$oww_base/$f"
done

# Silero VAD ONNX (upstream relocated).
silero_url="https://raw.githubusercontent.com/snakers4/silero-vad/master/src/silero_vad/data/silero_vad.onnx"
[ -f "$models_dir/silero_vad.onnx" ] || curl -fsSL -o "$models_dir/silero_vad.onnx" "$silero_url"

# Kokoro-82M (default TTS, Apache 2.0, ~310 Mo + 1 voix ~520 ko).
# Piper a été retiré de la stack par défaut ; eSpeak (apt) est le fallback.
kokoro_dir="${XDG_DATA_HOME:-$HOME/.local/share}/jarvis/kokoro"
kokoro_voices="$kokoro_dir/voices"
mkdir -p "$kokoro_voices"
kokoro_base="https://huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX/resolve/main"
[ -f "$kokoro_dir/kokoro-v1.0.onnx" ] || \
    wget -O "$kokoro_dir/kokoro-v1.0.onnx" "$kokoro_base/onnx/model.onnx"
[ -f "$kokoro_dir/tokenizer.json" ] || \
    wget -O "$kokoro_dir/tokenizer.json" "$kokoro_base/tokenizer.json"

# Voices: im_nicola = default (masculine, accent italien sur phonèmes FR);
# ff_siwis = féminine FR pure; bm_george/am_michael/em_alex = options.
[ -f "$kokoro_voices/am_onyx.bin" ] || \
    wget -O "$kokoro_voices/am_onyx.bin" "$kokoro_base/voices/am_onyx.bin"

echo "== Config =="
cfg_dir="${XDG_CONFIG_HOME:-$HOME/.config}/jarvis"
mkdir -p "$cfg_dir"
if [ ! -f "$cfg_dir/config.toml" ]; then
    cat > "$cfg_dir/config.toml" <<EOF
# Auto-generated by setup.sh — override anything here.
[stt]
model = "$models_dir/ggml-medium.bin"

[llm]
model = "$models_dir/qwen2.5-3b-instruct-q4_k_m.gguf"

[wake.clap]
# Off: the band-pass energy detector also catches keyboard clicks and
# broadband transients. Flip to true if you want hands-free activation
# in a quiet room.
enabled = false

[wake.wakeword]
model = "$models_dir/hey_jarvis_v0.1.onnx"

[tts]
engine = "kokoro"

[tts.kokoro]
model = "$kokoro_dir/kokoro-v1.0.onnx"
tokenizer = "$kokoro_dir/tokenizer.json"
voices_dir = "$kokoro_voices"
# Default: am_onyx (timbre grave, archétype Jarvis) sur phonèmes FR.
# Pour tester d'autres voix : jarvis tts-preview --voice <name>.
voice = "am_onyx"
speed = 1.0
language = "fr"
EOF
fi

echo "== Build + install =="
cargo install --path crates/jarvis --locked

echo "== Desktop integration =="
mkdir -p "$HOME/.config/systemd/user" "$HOME/.local/share/applications"
cp packaging/jarvis.service "$HOME/.config/systemd/user/"
cp packaging/jarvis.desktop "$HOME/.local/share/applications/"
systemctl --user daemon-reload

# Whisper hallucinates on faint audio: ensure the default mic is unmuted and
# at a reasonable level. Idempotent.
if command -v wpctl >/dev/null 2>&1; then
    wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 0 2>/dev/null || true
    cur=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ 2>/dev/null | awk '{print $2}')
    awk_under() { awk -v v="$1" -v t="0.7" 'BEGIN{exit !(v+0 < t+0)}'; }
    if [ -n "$cur" ] && awk_under "$cur"; then
        echo "Bumping default mic from $cur to 0.85"
        wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 0.85 2>/dev/null || true
    fi
fi

echo "== GNOME hotkey (Super+J → Listen) =="
# Idempotent: append our binding path if not already present, then write the
# binding triple. Works on Pop!_OS 24.04 GNOME 46.
if command -v gsettings >/dev/null 2>&1; then
    schema_kb="org.gnome.settings-daemon.plugins.media-keys"
    binding_path="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/jarvis-listen/"
    current=$(gsettings get "$schema_kb" custom-keybindings 2>/dev/null || echo "@as []")
    if ! echo "$current" | grep -q "jarvis-listen"; then
        # Strip surrounding @as / brackets, splice in our path.
        cleaned=$(echo "$current" | sed -E "s/^@as //; s/^\[//; s/\]$//")
        if [ -z "$cleaned" ] || [ "$cleaned" = " " ]; then
            new="['$binding_path']"
        else
            new="[${cleaned}, '$binding_path']"
        fi
        gsettings set "$schema_kb" custom-keybindings "$new" || true
    fi
    schema_kb_custom="org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:$binding_path"
    gsettings set "$schema_kb_custom" name "Jarvis Listen" || true
    gsettings set "$schema_kb_custom" command \
        "busctl --user call org.jarvis.Assistant /org/jarvis/Assistant org.jarvis.Assistant Listen" || true
    gsettings set "$schema_kb_custom" binding "<Super>j" || true
fi

cat <<'EOF'

Setup terminé.

  Démarrer :     systemctl --user enable --now jarvis
  Logs :         journalctl --user -u jarvis -f
  Tester :       jarvis say "Bonjour Sir"
  Voix (A/B) :   jarvis tts-preview --voice im_nicola --text "Test de voix."
  État :         jarvis status
  Config :       jarvis config-path
EOF
